### ISSUE TITLE
Benjamin from the leaderboard

### ISSUE THREAD

**Issue by benjaminbhollon** [Stegallo/adventofcode#156]
Hey, Stegallo! Glad to have you on my private leaderboard!

One thing, though—what's your Fediverse username? (e.g., Mastodon) The leaderboard is for people there, but I'm having trouble figuring out who you are. ;)

Thanks!

**Comment by benjaminbhollon** [comment]
Never mind, I've figured it out. ;)

**Comment by Stegallo** [comment]
Feel free to open a PR on this repo with suggestions :-) if you want to
